name: non_steam_artwork
description: "A linux tool to update artwork for non-steam programs."
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  intl:
  flex_color_scheme: ^7.3.1
  gap:
  flutter_rust_bridge: 2.0.0-dev.24
  rust_lib_non_steam_artwork:
    path: rust_builder
  freezed_annotation:
  meta:
  path:
  path_provider:
  collection:
  flutter_riverpod: ^3.0.0-dev.3
  riverpod_annotation: ^3.0.0-dev.3
  native_context_menu: ^0.2.2+5
  super_drag_and_drop: ^0.8.5
  super_clipboard: ^0.8.5
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size
  menubar:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/menubar
  url_launcher:
  io: ^1.0.4
  clock:
  package_info_plus:
  device_info_plus:
  markdown_widget: ^2.3.2+3
  http:
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.13
  steamgriddb:
    git:
      url: https://github.com/defuncart/steamgriddb
      ref: main
  cached_network_image:
  flutter_cache_manager:
  dio:
  dio_cache_interceptor: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  arb_generator:
  freezed:
  build_runner:
  riverpod_generator: ^3.0.0-dev.11
  riverpod_lint: ^3.0.0-dev.4
  custom_lint:

flutter:
  uses-material-design: true
  generate: true

arb_generator:
  input_filepath: "assets_dev/loca/loca.csv"
  output_directory: "assets_dev/l10n"
  filename_prepend: ""
  csv_settings:
    delimiter: ";"
    base_index: 1
