name: non_steam_artwork
description: A linux tool to update artwork for non-Steam programs.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ^3.7.0
  flutter: ^3.29.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  intl:
  flex_color_scheme:
  gap:
  steam_shortcuts_util:
    path: packages/steam_shortcuts_util/
  freezed_annotation:
  meta:
  path:
  path_provider:
  collection:
  flutter_riverpod:
  riverpod_annotation:
  native_context_menu: ^0.2.2+5
  super_drag_and_drop: ^0.8.24
  super_clipboard: ^0.8.24
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size
  menubar:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/menubar
  url_launcher:
  io: ^1.0.5
  clock:
  package_info_plus:
  device_info_plus:
  markdown_widget: ^2.3.2
  http:
  hive_ce: ^2.11.2
  steamgriddb:
    git:
      url: https://github.com/defuncart/steamgriddb
      ref: main
  cached_network_image:
  flutter_cache_manager:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  arb_generator:
  freezed:
  build_runner:
  riverpod_generator:
  riverpod_lint:
  custom_lint:

flutter:
  uses-material-design: true
  generate: true

arb_generator:
  input_filepath: "assets_dev/loca/loca.csv"
  output_directory: "assets_dev/l10n"
  filename_prepend: ""
  csv_settings:
    delimiter: ";"
    base_index: 1
