name: non_steam_artwork
description: "A linux tool to update artwork for non-steam programs."
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  intl:
  flex_color_scheme: ^7.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  arb_generator:

flutter:
  uses-material-design: true
  generate: true

arb_generator:
  input_filepath: "assets_dev/loca/loca.csv"
  output_directory: "assets_dev/l10n"
  filename_prepend: ""
  csv_settings:
    delimiter: ";"
    base_index: 1
