[package]
name = "rust_lib_non_steam_artwork"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.0.0-dev.24"
steam_shortcuts_util = "1.1.8"
anyhow = { version = "1.0.75", features = ["backtrace"] }
